apriltag_ros: 
  ros__parameters:
    # setup (defaults)
    image_transport: compressed  
    family: 36h11         
    size: 0.1             
    profile: false       
    # tuning of detection (defaults)
    max_hamming: 0        
    detector:
      threads: 1          
      decimate: 2.0      
      blur: 0.0           
      refine: 1           
      sharpening: 0.25   
      debug: 0            

    pose_estimation_method: "pnp" # method for estimating the tag pose

    # (optional) list of tags
    # If defined, 'frames' and 'sizes' must have the same length as 'ids'.
    tag:
      ids:    [<id1>, <id2>, ...]         # tag IDs for which to publish transform
      frames: [<frame1>, <frame2>, ...]   # frame names
      sizes:  [<size1>, <size1>, ...]     # tag-specific edge size, overrides the default 'size'
      